#!/usr/bin/env python3
"""Merge expanded Qur'anic duas into assets/data/quranic_duas.json."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "data" / "quranic_duas.json"


def dua(
    id_,
    arabic,
    surah,
    ayah_start,
    meaning_en,
    meaning_fr,
    meaning_ar,
    categories,
    keywords,
    ayah_end=None,
):
    o = {
        "id": id_,
        "arabicText": arabic,
        "surah": surah,
        "ayahStart": ayah_start,
        "meaningEn": meaning_en,
        "meaningFr": meaning_fr,
        "meaningAr": meaning_ar,
        "categories": categories,
        "searchKeywords": keywords,
    }
    if ayah_end is not None:
        o["ayahEnd"] = ayah_end
    return o


EXTRA = [
    dua(
        "q_2_127",
        "رَبَّنَا تَقَبَّلْ مِنَّا ۖ إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ",
        2,
        127,
        "Our Lord, accept [this] from us. Indeed, You are the Hearing, the Knowing.",
        "Ô notre Seigneur, accepte ceci de nous. Tu es l’Audient, l’Omniscient.",
        "دعاء إبراهيم عند بناء البيت: طلب القبول.",
        ["success", "gratitude"],
        ["تقبل", "accept", "Ibrahim", "Kaaba"],
    ),
    dua(
        "q_2_128",
        "رَبَّنَا وَاجْعَلْنَا مُسْلِمَيْنِ لَكَ وَمِن ذُرِّيَّتِنَا أُمَّةً مُّسْلِمَةً لَّكَ وَأَرِنَا مَنَاسِكَنَا وَتُبْ عَلَيْنَا ۖ إِنَّكَ أَنتَ التَّوَّابُ الرَّحِيمُ",
        2,
        128,
        "Our Lord, make us Muslims [in submission] to You and from our descendants a Muslim nation to You. Show us our rites and accept our repentance. Indeed, You are the Accepting of repentance, the Merciful.",
        "Ô notre Seigneur, fais de nous des soumis à Toi et de notre descendance une communauté soumise ; montre-nous nos rites et accepte notre repentir.",
        "طلب الإسلام للذرية ومعرفة المناسك والتوبة.",
        ["guidance", "parents", "mercy"],
        ["Muslim", "descendants", "rites", "توبة"],
    ),
    dua(
        "q_2_250",
        "رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا وَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ",
        2,
        250,
        "Our Lord, pour upon us patience, plant firmly our feet, and give us victory over the disbelieving people.",
        "Ô notre Seigneur, déverse sur nous la patience, affermis nos pas et donne-nous la victoire sur le peuple mécréant.",
        "صبر وثبات ونصر عند لقاء الجموع.",
        ["patience", "protection", "success"],
        ["صبر", "patience", "victory", "ثبات"],
    ),
    dua(
        "q_3_16",
        "رَبَّنَا إِنَّنَا آمَنَّا فَاغْفِرْ لَنَا ذُنُوبَنَا وَقِنَا عَذَابَ النَّارِ",
        3,
        16,
        "Our Lord, we have believed, so forgive us our sins and protect us from the punishment of the Fire.",
        "Ô notre Seigneur, nous avons cru : pardonne nos péchés et préserve-nous du châtiment du Feu.",
        "الإيمان وطلب المغفرة والنجاة من النار.",
        ["forgiveness", "guidance", "protection"],
        ["آمنا", "fire", "forgive", "نار"],
    ),
    dua(
        "q_3_26",
        "رَبَّنَا مَا خَلَقْتَ هَٰذَا بَاطِلًا سُبْحَانَكَ فَقِنَا عَذَابَ النَّارِ",
        3,
        26,
        "Our Lord, You did not create this aimlessly; exalted are You. Protect us from the punishment of the Fire.",
        "Ô notre Seigneur, Tu n’as pas créé cela en vain ; gloire à Toi ! Préserve-nous du châtiment du Feu.",
        "التسبيح وطلب العصمة من عذاب النار.",
        ["guidance", "protection", "gratitude"],
        ["creation", "fire", "باطلا"],
    ),
    dua(
        "q_3_147",
        "رَبِّ اغْفِرْ لِي وَلِأَخِي وَأَدْخِلْنَا فِي رَحْمَتِكَ وَاجْعَلْنَا مِنَ الصَّالِحِينَ",
        3,
        147,
        "My Lord, forgive me and my brother, admit us into Your mercy, and make us among the righteous.",
        "Ô mon Seigneur, pardonne-moi et à mon frère, fais-nous entrer dans Ta miséricorde et place-nous parmi les pieux.",
        "مغفرة ورحمة وصلاح.",
        ["forgiveness", "mercy", "guidance"],
        ["Moses", "brother", "صالحين"],
    ),
    dua(
        "q_3_53",
        "رَبَّنَا آمَنَّا بِمَا أَنزَلْتَ وَاتَّبَعْنَا الرَّسُولَ فَاكْتُبْنَا مَعَ الشَّاهِدِينَ",
        3,
        53,
        "Our Lord, we have believed in what You revealed and followed the messenger; register us among the witnesses.",
        "Ô notre Seigneur, nous avons cru à ce que Tu as fait descendre et suivi le Messager : inscris-nous parmi les témoins.",
        "إقرار بالإيمان والاتباع.",
        ["guidance", "success"],
        ["witness", "messenger", "faith"],
    ),
    dua(
        "q_5_114",
        "رَبَّنَا أَنزِلْ عَلَيْنَا مَائِدَةً مِّنَ السَّمَاءِ تَكُونُ لَنَا عِيدًا لِّأَوَّلِنَا وَآخِرِنَا وَآيَةً مِّنكَ ۖ وَارْزُقْنَا وَأَنتَ خَيْرُ الرَّازِقِينَ",
        5,
        114,
        "Our Lord, send down to us a table from heaven as a festival and a sign from You; provide for us — You are the best of providers.",
        "Ô notre Seigneur, fais descendre une table du ciel, signe de Ta part ; nourris-nous — Tu es le meilleur des pourvoyeurs.",
        "آية ورزق من الله.",
        ["rizq", "gratitude", "success"],
        ["table", "maida", "provision", "رزق"],
    ),
    dua(
        "q_7_47",
        "رَبَّنَا لَا تَجْعَلْنَا مَعَ الْقَوْمِ الْظَّالِمِينَ",
        7,
        47,
        "Our Lord, do not place us with the wrongdoing people.",
        "Ô notre Seigneur, ne nous place pas avec le peuple injuste.",
        "العصمة من مصاحبة الظالمين.",
        ["protection", "guidance"],
        ["wrongdoers", "ظالمين"],
    ),
    dua(
        "q_7_155",
        "أَنتَ وَلِيُّنَا فَاغْفِرْ لَنَا وَارْحَمْنَا وَأَنتَ خَيْرُ الْغَافِرِينَ",
        7,
        155,
        "You are our Protector, so forgive us and have mercy upon us. You are the best of forgivers.",
        "Tu es notre Protecteur : pardonne-nous et fais-nous miséricorde — Tu es le meilleur des pardonneurs.",
        "ولاية ومغفرة ورحمة.",
        ["forgiveness", "mercy", "guidance"],
        ["forgiver", "ولي"],
    ),
    dua(
        "q_7_151",
        "رَبَّنَا اغْفِرْ لِي وَلِأَخِي وَأَدْخِلْنَا فِي رَحْمَتِكَ وَاجْعَلْنَا مِنَ الصَّالِحِينَ",
        7,
        151,
        "Our Lord, forgive me and my brother, admit us into Your mercy, and make us among the righteous.",
        "Ô notre Seigneur, pardonne-moi et à mon frère, fais-nous entrer dans Ta miséricorde.",
        "مغفرة ورحمة وصلاح.",
        ["forgiveness", "mercy"],
        ["brother", "righteous"],
    ),
    dua(
        "q_10_85_86",
        "رَبَّنَا لَا تَجْعَلْنَا فِتْنَةً لِّلْقَوْمِ الْظَّالِمِينَ * وَنجِّنَا بِرَحْمَتِكَ مِنَ الْقَوْمِ الْكَافِرِينَ",
        10,
        85,
        "Our Lord, do not make us a trial for the wrongdoing people; save us by Your mercy from the disbelieving people.",
        "Ô notre Seigneur, ne fais pas de nous une épreuve pour les injustes ; sauve-nous par Ta miséricorde du peuple mécréant.",
        "العصمة من الفتنة والنجاة بالرحمة.",
        ["protection", "mercy"],
        ["Moses", "trial", "save", "fitna"],
        ayah_end=86,
    ),
    dua(
        "q_12_101",
        "رَبِّ قَدْ آتَيْتَنِي مِنَ الْمُلْكِ وَعَلَّمْتَنِي مِن تَأْوِيلِ الْأَحَادِيثِ ۚ فَاطِرَ السَّمَاوَاتِ وَالْأَرْضِ أَنتَ وَلِيِّي فِي الدُّنْيَا وَالْآخِرَةِ ۖ تَوَفَّنِي مُسْلِمًا وَأَلْحِقْنِي بِالصَّالِحِينَ",
        12,
        101,
        "My Lord, You have given me sovereignty and taught me the interpretation of events. Creator of the heavens and earth, You are my protector in this world and the Hereafter. Cause me to die a Muslim and join me with the righteous.",
        "Ô mon Seigneur, Tu m’as donné du pouvoir et enseigné l’interprétation ; Tu es mon protecteur ici-bas et dans l’au-delà. Fais-moi mourir musulman et joins-moi aux pieux.",
        "دعاء يوسف: شكر النعمة وطلب الخاتمة على الإسلام.",
        ["success", "guidance", "gratitude"],
        ["Yusuf", "Joseph", "righteous", "مسلما"],
    ),
    dua(
        "q_14_40",
        "رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِن ذُرِّيَّتِي ۚ رَبَّنَا وَتَقَبَّلْ دُعَاءِ",
        14,
        40,
        "My Lord, make me an establisher of prayer, and from my descendants. Our Lord, accept my supplication.",
        "Ô mon Seigneur, fais que j’accomplisse la prière ainsi qu’une partie de ma descendance ; accepte ma supplication.",
        "إقامة الصلاة للذرية وقبول الدعاء.",
        ["parents", "guidance", "success"],
        ["prayer", "salat", "descendants", "صلاة"],
    ),
    dua(
        "q_17_80",
        "رَبِّ أَدْخِلْنِي مُدْخَلَ صِدْقٍ وَأَخْرِجْنِي مُخْرَجَ صِدْقٍ وَاجْعَل لِّي مِن لَّدُنكَ سُلْطَانًا نَّصِيرًا",
        17,
        80,
        "My Lord, let me enter a sound entrance and exit a sound exit and grant me from Yourself a supporting authority.",
        "Ô mon Seigneur, fais-moi entrer par une entrée de vérité et sortir par une sortie de vérité ; accorde-moi de Ta part un pouvoir aidant.",
        "دعاء الهجرة: صدق الدخول والخروج والنصر.",
        ["success", "guidance", "protection"],
        ["hijra", "migration", "صدق", "authority"],
    ),
    dua(
        "q_19_4",
        "رَبِّ لَا تَذَرْنِي فَرْدًا وَأَنتَ خَيْرُ الْوَارِثِينَ",
        19,
        4,
        "My Lord, do not leave me alone, and You are the best of inheritors.",
        "Ô mon Seigneur, ne me laisse pas seul — Tu es le meilleur des héritiers.",
        "دعاء زكريا: طلب الذرية الصالحة.",
        ["parents", "family", "mercy"],
        ["Zachariah", "offspring", "ذرية", "وارثين"],
    ),
    dua(
        "q_21_89",
        "رَبِّ لَا تَذَرْنِي فَرْدًا وَأَنتَ خَيْرُ الْوَارِثِينَ",
        21,
        89,
        "My Lord, do not leave me alone, and You are the best of inheritors.",
        "Ô mon Seigneur, ne me laisse pas seul — Tu es le meilleur des héritiers.",
        "دعاء زكريا عليه السلام.",
        ["parents", "family", "mercy"],
        ["Zachariah", "offspring"],
    ),
    dua(
        "q_23_29",
        "رَبِّ انصُرْنِي عَلَى الْقَوْمِ الْمُفْسِدِينَ",
        23,
        29,
        "My Lord, support me against the corrupting people.",
        "Ô mon Seigneur, aide-moi contre le peuple corrupteur.",
        "طلب النصر على المفسدين.",
        ["protection", "success"],
        ["support", "corrupt", "نصر"],
    ),
    dua(
        "q_23_97_98",
        "رَبِّ أَعُوذُ بِكَ مِنْ هَمَزَاتِ الشَّيَاطِينِ * وَأَعُوذُ بِكَ رَبِّ أَن يَحْضُرُونِ",
        23,
        97,
        "My Lord, I seek refuge in You from the incitements of devils, and I seek refuge in You, my Lord, lest they be present with me.",
        "Ô mon Seigneur, je cherche refuge auprès de Toi contre les suggestions des diables et contre leur présence.",
        "الاستعاذة من وسوسة الشياطين.",
        ["protection", "guidance"],
        ["devil", "shaytan", "refuge", "وسوسة"],
        ayah_end=98,
    ),
    dua(
        "q_23_118",
        "رَبِّ اغْفِرْ وَارْحَمْ وَأَنتَ خَيْرُ الرَّاحِمِينَ",
        23,
        118,
        "My Lord, forgive and have mercy, and You are the best of the merciful.",
        "Ô mon Seigneur, pardonne et fais miséricorde — Tu es le meilleur des miséricordieux.",
        "مغفرة ورحمة.",
        ["forgiveness", "mercy"],
        ["forgive", "راحمين"],
    ),
    dua(
        "q_25_65",
        "رَبَّنَا اصْرِفْ عَنَّا عَذَابَ جَهَنَّمَ ۖ إِنَّ عَذَابَهَا كَانَ غَرَامًا",
        25,
        65,
        "Our Lord, avert from us the punishment of Hell. Indeed, its punishment is ever adhering.",
        "Ô notre Seigneur, détourne de nous le châtiment de l’Enfer — son châtiment est permanent.",
        "الاستعاذة من عذاب جهنم.",
        ["protection", "forgiveness"],
        ["Hell", "jahannam", "عذاب"],
    ),
    dua(
        "q_26_83_85",
        "رَبِّ هَبْ لِي حُكْمًا وَأَلْحِقْنِي بِالصَّالِحِينَ * وَاجْعَل لِّي لِسَانَ صِدْقٍ فِي الْآخِرِينَ * وَاجْعَلْنِي مِن وَرَثَةِ جَنَّةِ النَّعِيمِ",
        26,
        83,
        "My Lord, grant me authority and join me with the righteous, grant me a mention of honor among later generations, and place me among the inheritors of the Garden of Pleasure.",
        "Ô mon Seigneur, accorde-moi sagesse et autorité, joins-moi aux pieux, fais-moi une louange durable et place-moi parmi les héritiers du Jardin.",
        "دعاء إبراهيم: حكم وصلاح وذكر صالح والجنة.",
        ["success", "guidance", "parents"],
        ["Ibrahim", "righteous", "Paradise"],
        ayah_end=85,
    ),
    dua(
        "q_27_19",
        "رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ الَّتِي أَنْعَمْتَ عَلَيَّ وَعَلَىٰ وَالِدَيَّ وَأَنْ أَعْمَلَ صَالِحًا تَرْضَاهُ وَأَدْخِلْنِي بِرَحْمَتِكَ فِي عِبَادِكَ الصَّالِحِينَ",
        27,
        19,
        "My Lord, enable me to be grateful for Your favor upon me and upon my parents and to do righteousness You approve, and admit me by Your mercy among Your righteous servants.",
        "Ô mon Seigneur, inspire-moi la gratitude pour Tes bienfaits sur moi et mes parents, l’œuvre qui Te plaît, et fais-moi entrer parmi Tes serviteurs pieux.",
        "شكر النعمة والعمل الصالح.",
        ["gratitude", "parents", "guidance"],
        ["Sulayman", "thank", "شكر"],
    ),
    dua(
        "q_28_24",
        "رَبِّ إِنِّي لِمَا أَنزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ",
        28,
        24,
        "My Lord, indeed I am, for whatever good You send down to me, in need.",
        "Ô mon Seigneur, j’ai grand besoin de tout bien que Tu fais descendre vers moi.",
        "دعاء موسى عند الزواج: الافتقار لخير الله.",
        ["rizq", "gratitude", "success"],
        ["Moses", "need", "خير", "provision"],
    ),
    dua(
        "q_37_100",
        "رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ",
        37,
        100,
        "My Lord, grant me [a child] from among the righteous.",
        "Ô mon Seigneur, accorde-moi [un enfant] parmi les pieux.",
        "طلب الذرية الصالحة.",
        ["parents", "family", "mercy"],
        ["offspring", "child", "صالحين"],
    ),
    dua(
        "q_38_35",
        "رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ ۖ إِنَّكَ أَنتَ التَّوَّابُ الرَّحِيمُ",
        38,
        35,
        "My Lord, forgive me and accept my repentance. Indeed, You are the Accepting of repentance, the Merciful.",
        "Ô mon Seigneur, pardonne-moi et accepte mon repentir — Tu es l’Accueillant au repentir, le Miséricordieux.",
        "مغفرة وتوبة.",
        ["forgiveness", "mercy"],
        ["repent", "توبة"],
    ),
    dua(
        "q_40_7",
        "رَبَّنَا وَسِعْتَ كُلَّ شَيْءٍ رَّحْمَةً وَعِلْمًا فَاغْفِرْ لِلَّذِينَ تَابُوا وَاتَّبَعُوا سَبِيلَكَ وَقِهِمْ عَذَابَ الْجَحِيمِ",
        40,
        7,
        "Our Lord, You have encompassed all things in mercy and knowledge, so forgive those who have repented and followed Your way and protect them from the punishment of Hellfire.",
        "Ô notre Seigneur, Ta miséricorde et Ta science embrassent toute chose : pardonne à ceux qui se repentent, suivent Ton chemin et préserve-les du châtiment de la Fournaise.",
        "مغفرة للتابعين والعصمة من الجحيم.",
        ["forgiveness", "mercy", "guidance"],
        ["repent", "Hell", "path"],
    ),
    dua(
        "q_40_8",
        "رَبَّنَا وَأَدْخِلْهُمْ جَنَّاتِ عَدْنٍ الَّتِي وَعَدتَّهُمْ وَمَن صَلَحَ مِنْ آبَائِهِمْ وَأَزْوَاجِهِمْ وَذُرِّيَّاتِهِمْ ۚ إِنَّكَ أَنتَ الْعَزِيزُ الْحَكِيمُ",
        40,
        8,
        "Our Lord, admit them to gardens of perpetual residence which You have promised them and whoever was righteous among their fathers, spouses, and offspring. Indeed, You are the Exalted in Might, the Wise.",
        "Ô notre Seigneur, fais-les entrer aux jardins d’Éden promis, eux et les pieux parmi leurs pères, épouses et descendants.",
        "دعاء الملائكة للمؤمنين بالجنة.",
        ["success", "parents", "family"],
        ["Paradise", "family", "جنة"],
    ),
    dua(
        "q_46_15",
        "رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ الَّتِي أَنْعَمْتَ عَلَيَّ وَعَلَىٰ وَالِدَيَّ وَأَنْ أَعْمَلَ صَالِحًا تَرْضَاهُ وَأَصْلِحْ لِي فِي ذُرِّيَّتِي ۖ إِنِّي تُبْتُ إِلَيْكَ وَإِنِّي مِنَ الْمُسْلِمِينَ",
        46,
        15,
        "My Lord, enable me to be grateful for Your favor upon me and my parents and to do righteousness You approve and correct for me my offspring. Indeed, I have repented to You, and I am of the Muslims.",
        "Ô mon Seigneur, inspire-moi gratitude, œuvre agréée et droiture pour ma descendance ; je me repens à Toi et je suis musulman.",
        "شكر وصلاح للذرية وتوبة.",
        ["gratitude", "parents", "guidance"],
        ["repent", "offspring", "شكر"],
    ),
    dua(
        "q_59_10",
        "رَبَّنَا اغْفِرْ لَنَا وَلِإِخْوَانِنَا الَّذِينَ سَبَقُونَا بِالْإِيمَانِ وَلَا تَجْعَلْ فِي قُلُوبِنَا غِلًّا لِّلَّذِينَ آمَنُوا رَبَّنَا إِنَّكَ رَءُوفٌ رَّحِيمٌ",
        59,
        10,
        "Our Lord, forgive us and our brothers who preceded us in faith and put not in our hearts resentment toward those who have believed. Our Lord, indeed You are Kind and Merciful.",
        "Ô notre Seigneur, pardonne-nous et à nos frères qui nous ont précédés dans la foi ; ne mets pas dans nos cœurs de rancune envers les croyants.",
        "مغفرة للمؤمنين وصفاء القلوب.",
        ["forgiveness", "mercy", "guidance"],
        ["brothers", "faith", "resentment"],
    ),
    dua(
        "q_66_11",
        "رَبِّ ابْنِ لِي عِندَكَ بَيْتًا فِي الْجَنَّةِ وَنجِّنِي مِن فِرْعَوْنَ وَعَمَلِهِ وَنجِّنِي مِنَ الْقَوْمِ الظَّالِمِينَ",
        66,
        11,
        "My Lord, build for me near You a house in Paradise and save me from Pharaoh and his deeds and save me from the wrongdoing people.",
        "Ô mon Seigneur, construis-moi près de Toi une demeure au Paradis et sauve-moi de Pharaon et des injustes.",
        "دعاء امرأة فرعون: بيت في الجنة والنجاة.",
        ["success", "protection", "guidance"],
        ["Paradise", "Pharaoh", "Asiya"],
    ),
    dua(
        "q_71_28",
        "رَبِّ اغْفِرْ لِي وَلِوَالِدَيَّ وَلِمَن دَخَلَ بَيْتِيَ مُؤْمِنًا وَلِلْمُؤْمِنِينَ وَالْمُؤْمِنَاتِ",
        71,
        28,
        "My Lord, forgive me and my parents and whoever enters my house believing and the believing men and believing women.",
        "Ô mon Seigneur, pardonne-moi, à mes parents, à quiconque entre ma demeure croyant et aux croyants et croyantes.",
        "استغفار واسع للمؤمنين.",
        ["forgiveness", "parents", "mercy"],
        ["Nuh", "believers", "والد"],
    ),
    dua(
        "q_2_38",
        "رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ",
        2,
        38,
        "Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.",
        "Ô notre Seigneur, nous nous sommes fait du tort ; si Tu ne nous pardonnes pas et ne nous fais pas miséricorde, nous serons perdants.",
        "دعاء آدم وحواء بعد الذنب.",
        ["forgiveness", "mercy"],
        ["Adam", "wrong", "خاسرين"],
    ),
    dua(
        "q_4_75",
        "رَبَّنَا أَخْرِجْنَا مِنْ هَٰذِهِ الْقَرْيَةِ الظَّالِمِ أَهْلُهَا وَاجْعَل لَّنَا مِن لَّدُنكَ وَلِيًّا وَاجْعَل لَّنَا مِن لَّدُنكَ نَصِيرًا",
        4,
        75,
        "Our Lord, take us out of this city of oppressive people and appoint for us from Yourself a protector and appoint for us from Yourself a helper.",
        "Ô notre Seigneur, fais-nous sortir de cette cité dont les habitants sont injustes ; accorde-nous un protecteur et un secoureur.",
        "النجاة من الظلم وطلب الولي والنصير.",
        ["protection", "guidance"],
        ["oppression", "helper", "ولي"],
    ),
    dua(
        "q_9_129",
        "حَسْبِيَ اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ ۖ عَلَيْهِ تَوَكَّلْتُ ۖ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ",
        9,
        129,
        "Sufficient for me is Allah; there is no deity except Him. On Him I have relied, and He is the Lord of the Great Throne.",
        "Allah me suffit : il n’y a de divinité que Lui. Je m’en remets à Lui ; Il est le Seigneur du Trône immense.",
        "الاكتفاء بالله والتوكل.",
        ["refuge", "protection", "guidance"],
        ["hasbiya", "tawakkul", "trust"],
    ),
    dua(
        "q_1_1_7",
        "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ * الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ * الرَّحْمَٰنِ الرَّحِيمِ * مَالِكِ يَوْمِ الدِّينِ * إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ * اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ * صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
        1,
        1,
        "In the name of Allah, the Entirely Merciful, the Especially Merciful. All praise is due to Allah, Lord of the worlds… Guide us to the straight path.",
        "Au nom d’Allah, le Tout Miséricordieux, le Très Miséricordieux. Louange à Allah, Seigneur des mondes… Guide-nous dans le droit chemin.",
        "سورة الفاتحة: دعاء وعبادة في كل ركعة.",
        ["guidance", "mercy", "gratitude"],
        ["Fatiha", "opening", "هدى", "prayer"],
        ayah_end=7,
    ),
    dua(
        "q_113_1_4",
        "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ * مِن شَرِّ مَا خَلَقَ * وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ * وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ * وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ",
        113,
        1,
        "Say, I seek refuge in the Lord of daybreak, from the evil of what He created…",
        "Dis : « Je cherche refuge auprès du Seigneur de l’aube, contre le mal de ce qu’Il a créé… »",
        "الاستعاذة برب الفلق من الشرور.",
        ["protection", "guidance"],
        ["Falaq", "refuge", "evil", "معوذتين"],
        ayah_end=4,
    ),
    dua(
        "q_114_1_5",
        "قُلْ أَعُوذُ بِرَبِّ النَّاسِ * مَلِكِ النَّاسِ * إِلَٰهِ النَّاسِ * مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ * الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ * مِنَ الْجِنَّةِ وَالنَّاسِ",
        114,
        1,
        "Say, I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer…",
        "Dis : « Je cherche refuge auprès du Seigneur des hommes… contre le mal du mauvais conseiller furtif. »",
        "الاستعاذة من الوسوسة في القلوب.",
        ["protection", "guidance"],
        ["Nas", "whisper", "anxiety", "وسوسة"],
        ayah_end=5,
    ),
    dua(
        "q_2_201b",
        "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
        2,
        200,
        "Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.",
        "Ô notre Seigneur, le bien ici-bas et dans l’au-delà, et préserve-nous du Feu.",
        "من أدعية الحج والعمرة في القرآن.",
        ["success", "rizq", "protection"],
        ["hajj", "umrah", "حسنة", "dunya"],
    ),
    dua(
        "q_3_38",
        "رَبِّ هَبْ لِي مِن لَّدُنكَ ذُرِّيَّةً طَيِّبَةً ۖ إِنَّكَ سَمِيعُ الدُّعَاءِ",
        3,
        38,
        "My Lord, grant me from Yourself a good offspring. Indeed, You are the Hearer of supplication.",
        "Ô mon Seigneur, accorde-moi de Ta part une descendance pure — Tu entends la supplication.",
        "دعاء زكريا لولد صالح.",
        ["parents", "family", "mercy"],
        ["offspring", "Yahya", "سميع"],
    ),
    dua(
        "q_3_147b",
        "رَبَّنَا اغْفِرْ لَنَا ذُنُوبَنَا وَإِسْرَافَنَا فِي أَمْرِنَا وَثَبِّتْ أَقْدَامَنَا وَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ",
        3,
        148,
        "Our Lord, forgive us our sins and our excesses in our affairs, plant firmly our feet, and give us victory over the disbelieving people.",
        "Ô notre Seigneur, pardonne nos péchés et nos excès, affermis nos pas et donne-nous la victoire.",
        "مغفرة وثبات ونصر.",
        ["forgiveness", "patience", "success"],
        ["victory", "ثبات"],
    ),
    dua(
        "q_8_30",
        "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
        8,
        30,
        "Sufficient for us is Allah, and He is the best Disposer of affairs.",
        "Allah nous suffit : quel excellent garant !",
        "عند الحزب والخوف: التوكل على الله.",
        ["refuge", "protection", "patience"],
        ["hasbunallah", "wakil", "trust"],
    ),
    dua(
        "q_10_10",
        "لَهُمْ دَارُ السَّلَامِ عِندَ رَبِّهِمْ ۖ وَهُوَ وَلِيُّهُم بِمَا كَانُوا يَعْمَلُونَ",
        10,
        10,
        "For them is the Home of Peace with their Lord, and He is their protector because of what they used to do.",
        "Ils auront la demeure de paix auprès de leur Seigneur, qui est leur protecteur pour leurs œuvres.",
        "وعد للمحسنين بدار السلام.",
        ["success", "guidance", "mercy"],
        ["peace", "dar salam", "reward"],
    ),
    dua(
        "q_16_30",
        "رَبَّنَا آمَنَّا فَاغْفِرْ لَنَا وَارْحَمْنَا وَأَنتَ خَيْرُ الرَّاحِمِينَ",
        16,
        30,
        "Our Lord, we have believed, so forgive us and have mercy upon us, and You are the best of the merciful.",
        "Ô notre Seigneur, nous avons cru : pardonne-nous et fais-nous miséricorde.",
        "دعاء المتقين عند الحساب.",
        ["forgiveness", "mercy", "guidance"],
        ["believed", "راحمين"],
    ),
    dua(
        "q_18_14",
        "رَبُّنَا رَبُّ السَّمَاوَاتِ وَالْأَرْضِ لَن نَّدْعُوَ مِن دُونِهِ إِلَٰهًا ۖ لَّقَدْ قُلْنَا إِذًا شَطَطًا",
        18,
        14,
        "Our Lord is the Lord of the heavens and the earth. We will not invoke besides Him any deity; that would be an outrageous assertion.",
        "Notre Seigneur est le Seigneur des cieux et de la terre ; nous n’invoquerons pas d’autre divinité — ce serait un dire monstrueux.",
        "توحيد أصحاب الكهف.",
        ["guidance", "protection"],
        ["cave", "tawhid", "توحيد"],
    ),
    dua(
        "q_20_32",
        "وَاجْعَل لِّي وَزِيرًا مِّنْ أَهْلِي",
        20,
        32,
        "And appoint for me a minister from my family.",
        "Et désigne-moi un auxiliaire parmi les miens.",
        "دعاء موسى: طلب معين من أهله (هارون).",
        ["success", "guidance"],
        ["Moses", "Harun", "minister"],
    ),
    dua(
        "q_21_112",
        "رَبِّ احْكُم بِالْحَقِّ ۗ وَرَبُّنَا الرَّحْمَٰنُ الْمُسْتَعَانُ عَلَىٰ مَا تَصِفُونَ",
        21,
        112,
        "My Lord, judge in truth. Our Lord is the Most Merciful, the One whose help is sought against what you describe.",
        "Ô mon Seigneur, juge en toute vérité ! Notre Seigneur est le Tout Miséricordieux dont on implore le secours.",
        "اللجوء إلى حكم الله الحق.",
        ["guidance", "protection"],
        ["truth", "judge", "help"],
    ),
    dua(
        "q_23_109b",
        "رَبَّنَا آمَنَّا فَاغْفِرْ لَنَا وَارْحَمْنَا وَأَنتَ خَيْرُ الرَّاحِمِينَ",
        23,
        109,
        "Our Lord, we have believed, so forgive us and have mercy upon us, and You are the best of the merciful.",
        "Ô notre Seigneur, nous avons cru : pardonne et fais miséricorde.",
        "إيمان ثم مغفرة ورحمة.",
        ["forgiveness", "mercy", "guidance"],
        ["believed"],
    ),
    dua(
        "q_27_62",
        "أَمَّن يُجِيبُ الْمُضْطَرَّ إِذَا دَعَاهُ وَيَكْشِفُ السُّوءَ",
        27,
        62,
        "Is He [not best] who responds to the desperate when he calls upon Him and removes evil?",
        "N’est-ce pas Lui qui répond à l’angoissé quand il L’invoque et qui enlève le mal ?",
        "الإجابة للمضطر وكشف السوء.",
        ["mercy", "healing", "protection"],
        ["distress", "mudtar", "anxiety", "مضطر"],
    ),
    dua(
        "q_28_16",
        "رَبِّ إِنِّي ظَلَمْتُ نَفْسِي فَاغْفِرْ لِي",
        28,
        16,
        "My Lord, indeed I have wronged myself, so forgive me.",
        "Ô mon Seigneur, je me suis fait du tort : pardonne-moi.",
        "توبة موسى بعد الخطأ.",
        ["forgiveness", "mercy"],
        ["Moses", "wrong", "توبة"],
    ),
    dua(
        "q_40_60",
        "ادْعُونِي أَسْتَجِبْ لَكُمْ",
        40,
        60,
        "Call upon Me; I will respond to you.",
        "Invoquez-Moi, Je vous répondrai.",
        "وعد الإجابة للداعين.",
        ["guidance", "mercy"],
        ["call", "respond", "دعاء", "استجابة"],
    ),
    dua(
        "q_14_35",
        "رَبِّ اجْعَلْ هَٰذَا الْبَلَدَ آمِنًا وَاجْنُبْنِي وَبَنِيَّ أَن نَّعْبُدَ الْأَصْنَامَ",
        14,
        35,
        "My Lord, make this city secure and keep me and my sons away from worshipping idols.",
        "Ô mon Seigneur, fais de cette cité un lieu sûr et éloigne-moi ainsi que mes fils de l’adoration des idoles.",
        "دعاء إبراهيم لمكة والعصمة من الشرك.",
        ["protection", "parents", "guidance"],
        ["Makkah", "idols", "security"],
    ),
    dua(
        "q_14_36",
        "رَبِّ إِنَّهُنَّ أَضْلَلْنَ كَثِيرًا مِّنَ النَّاسِ ۖ فَمَن تَبِعَنِي فَإِنَّهُ مِنِّي",
        14,
        36,
        "My Lord, indeed they have led astray many among the people. So whoever follows me — then he is of me.",
        "Ô mon Seigneur, elles ont égaré beaucoup de gens ; quiconque me suit est des miens.",
        "طلب الهداية للأمة ودفع ضلال الشرك.",
        ["guidance", "parents"],
        ["Ibrahim", "followers"],
    ),
    dua(
        "q_17_24c",
        "وَاخْفِضْ لَهُمَا جَنَاحَ الذُّلِّ مِنَ الرَّحْمَةِ",
        17,
        24,
        "And lower to them the wing of humility out of mercy.",
        "Et abaisse pour eux l’aile de l’humilité par miséricorde.",
        "أمر برّ الوالدين (سياق الدعاء والبر).",
        ["parents", "mercy", "gratitude"],
        ["humility", "والدين"],
    ),
    dua(
        "q_19_6",
        "يَا يَحْيَىٰ خُذِ الْكِتَابَ بِقُوَّةٍ",
        19,
        12,
        "O John, take the Scripture with determination.",
        "Ô Yahya, tiens fermement le Livre !",
        "توجيه وقوة في اتباع الكتاب.",
        ["guidance", "knowledge"],
        ["Yahya", "John", "Scripture"],
    ),
    dua(
        "q_21_76",
        "وَنَجَّيْنَاهُ مِنَ الْقَوْمِ الَّذِينَ كَذَّبُوا بِآيَاتِنَا ۚ إِنَّهُمْ كَانُوا قَوْمَ سَوْءٍ فَأَنجَيْنَاهُ",
        21,
        76,
        "And We saved him from the people who denied Our signs. Indeed, they were a people of evil, so We saved him.",
        "Nous l’avons sauvé du peuple qui démentait Nos signes — c’était un peuple mauvais.",
        "دعاء نوح والنجاة من القوم.",
        ["protection", "patience"],
        ["Nuh", "Noah", "saved"],
    ),
    dua(
        "q_23_115",
        "رَبِّ فَلَا تَجْعَلْنِي فِي الْقَوْمِ الظَّالِمِينَ",
        23,
        115,
        "My Lord, then do not place me among the wrongdoing people.",
        "Ô mon Seigneur, ne me place pas parmi les injustes.",
        "النجاة من مصاحبة الظالمين.",
        ["protection", "guidance"],
        ["wrongdoers"],
    ),
    dua(
        "q_26_86",
        "وَاغْفِرْ لِأَبِي إِنَّهُ كَانَ مِنَ الضَّالِّينَ",
        26,
        86,
        "And forgive my father. Indeed, he has been of those astray.",
        "Et pardonne à mon père : il était parmi les égarés.",
        "دعاء إبراهيم لأبيه (قبل بيان التحريم).",
        ["parents", "forgiveness"],
        ["father", "Ibrahim"],
    ),
    dua(
        "q_27_19b",
        "رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ",
        27,
        19,
        "My Lord, enable me to be grateful for Your favor.",
        "Ô mon Seigneur, inspire-moi la gratitude pour Ta grâce.",
        "شكر النعمة.",
        ["gratitude", "success"],
        ["thank", "نعمة"],
    ),
    dua(
        "q_28_22",
        "رَبِّ نَجِّنِي مِنَ الْقَوْمِ الظَّالِمِينَ",
        28,
        22,
        "My Lord, save me from the wrongdoing people.",
        "Ô mon Seigneur, sauve-moi du peuple injuste.",
        "دعاء موسى في الهجرة إلى مدين.",
        ["protection", "guidance"],
        ["Moses", "save", "ظالمين"],
    ),
    dua(
        "q_29_30",
        "رَبِّ انصُرْنِي عَلَى الْقَوْمِ الْمُفْسِدِينَ",
        29,
        30,
        "My Lord, support me against the corrupting people.",
        "Ô mon Seigneur, aide-moi contre le peuple corrupteur.",
        "نصر لوط على المفسدين.",
        ["protection", "success"],
        ["Lut", "support"],
    ),
    dua(
        "q_40_9",
        "وَقِهِمْ عَذَابَ الْجَحِيمِ",
        40,
        9,
        "And protect them from the punishment of Hellfire.",
        "Et préserve-les du châtiment de la Fournaise.",
        "دعاء الملائكة للمؤمنين.",
        ["protection", "forgiveness"],
        ["Hell", "جحيم"],
    ),
    dua(
        "q_46_16",
        "رَبَّنَا وَأَتْمِمْ لَنَا نُورَنَا وَاغْفِرْ لَنَا ۖ إِنَّكَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
        46,
        16,
        "Our Lord, perfect for us our light and forgive us. Indeed, You are over all things competent.",
        "Ô notre Seigneur, parachève notre lumière et pardonne-nous — Tu es Capable de toute chose.",
        "تمام النور والمغفرة يوم القيامة.",
        ["forgiveness", "guidance", "success"],
        ["light", "نور", "judgment"],
    ),
    dua(
        "q_60_5",
        "رَبَّنَا لَا تَجْعَلْنَا فِتْنَةً لِّلَّذِينَ كَفَرُوا وَاغْفِرْ لَنَا رَبَّنَا ۖ إِنَّكَ أَنتَ الْعَزِيزُ الْحَكِيمُ",
        60,
        5,
        "Our Lord, make us not a trial for those who disbelieved and forgive us. Our Lord, indeed You are Exalted in Might and Wise.",
        "Ô notre Seigneur, ne fais pas de nous une tentation pour les mécréants et pardonne-nous.",
        "العصمة من الفتنة والمغفرة.",
        ["protection", "forgiveness"],
        ["trial", "fitna"],
    ),
    dua(
        "q_66_8",
        "يَا أَيُّهَا الَّذِينَ آمَنُوا تُوبُوا إِلَى اللَّهِ تَوْبَةً نَّصُوحًا",
        66,
        8,
        "O you who believe, repent to Allah with sincere repentance.",
        "Ô vous qui croyez ! Repentez-vous à Allah d’un repentir sincère.",
        "أمر بالتوبة النصوح.",
        ["forgiveness", "guidance", "taqwa"],
        ["repent", "توبة"],
    ),
    dua(
        "q_2_286_open",
        "لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا",
        2,
        286,
        "Allah does not charge a soul except [with that within] its capacity.",
        "Allah n’impose à aucune âme une charge supérieure à sa capacité.",
        "تخفيف بعد دعاء المغفرة في آخر البقرة.",
        ["patience", "mercy"],
        ["capacity", "وسع", "ease"],
    ),
    dua(
        "q_3_54",
        "وَمَكَرُوا وَمَكَرَ اللَّهُ ۖ وَاللَّهُ خَيْرُ الْمَاكِرِينَ",
        3,
        54,
        "They plotted, and Allah plotted. And Allah is the best of planners.",
        "Ils ont comploté, Allah a comploté — Allah est le meilleur des stratèges.",
        "التوكل عند المكر: الله خير الماكرين.",
        ["protection", "guidance"],
        ["plot", "trust", "مكر"],
    ),
    dua(
        "q_8_62",
        "وَإِن يُرِيدُوا أَن يَصْلَحُوا يَجْعَلِ اللَّهُ بَيْنَهُمْ وَبَيْنَكَ صُلْحًا",
        8,
        62,
        "If they intend peace, then Allah will grant it between them and you.",
        "S’ils veulent la paix, Allah la fera entre eux et toi.",
        "طلب الصلح والأمان.",
        ["protection", "success"],
        ["peace", "صلح"],
    ),
    dua(
        "q_9_51",
        "قُل لَّن يُصِيبَنَا إِلَّا مَا كَتَبَ اللَّهُ لَنَا",
        9,
        51,
        "Say, nothing will befall us except what Allah has decreed for us.",
        "Dis : rien ne nous atteindra sauf ce qu’Allah a décrété pour nous.",
        "رضا بالقضاء والتوكل.",
        ["patience", "guidance", "refuge"],
        ["decree", "qadar", "trust"],
    ),
    dua(
        "q_12_86",
        "إِنَّمَا أَشْكُو بَثِّي وَحُزْنِي إِلَى اللَّهِ",
        12,
        86,
        "I only complain of my suffering and my grief to Allah.",
        "Je ne me plains de ma détresse et de mon chagrin qu’à Allah.",
        "دعاء يعقوب: الشكوى لله وحده.",
        ["patience", "healing", "mercy"],
        ["Yaqub", "grief", "anxiety", "حزن"],
    ),
    dua(
        "q_18_39",
        "وَلَوْلَا إِذْ دَخَلْتَ جَنَّتَكَ قُلْتَ مَا شَاءَ اللَّهُ لَا قُوَّةَ إِلَّا بِاللَّهِ",
        18,
        39,
        "Why did you not, when you entered your garden, say, ‘What Allah willed [has occurred]; there is no power except in Allah’?",
        "Pourquoi n’as-tu pas dit, en entrant dans ton jardin : « Ce qu’Allah veut ! Il n’y a de force qu’en Allah » ?",
        "الاعتراف بقوة الله وتواضع العبد.",
        ["gratitude", "guidance", "refuge"],
        ["masha Allah", "quwwa", "garden"],
    ),
    dua(
        "q_24_22",
        "وَلْيَعْفُوا وَلْيَصْفَحُوا ۗ أَلَا تُحِبُّونَ أَن يَغْفِرَ اللَّهُ لَكُمْ",
        24,
        22,
        "Let them pardon and overlook. Would you not like that Allah should forgive you?",
        "Qu’ils pardonnent et passent outre. N’aimez-vous pas qu’Allah vous pardonne ?",
        "حث على العفو لنيل مغفرة الله.",
        ["forgiveness", "mercy"],
        ["pardon", "عفو"],
    ),
    dua(
        "q_25_74b",
        "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ",
        25,
        74,
        "Our Lord, grant us from among our wives and offspring comfort to our eyes.",
        "Ô notre Seigneur, fais de nos épouses et descendants la joie de nos yeux.",
        "قرّة العين في الأهل والذرية.",
        ["family", "parents", "gratitude"],
        ["children", "wife", "قررة"],
    ),
    dua(
        "q_35_34",
        "الْحَمْدُ لِلَّهِ الَّذِي أَذْهَبَ عَنَّا الْحَزَنَ",
        35,
        34,
        "Praise to Allah, who has removed from us sorrow.",
        "Louange à Allah qui a éloigné de nous la tristesse.",
        "حمد الله على إذهاب الحزن في الجنة (أمل للمؤمن).",
        ["gratitude", "mercy", "healing"],
        ["praise", "sorrow", "حزن", "anxiety"],
    ),
    dua(
        "q_40_7b",
        "رَبَّنَا أَتْمِمْ لَنَا نُورَنَا",
        66,
        8,
        "Our Lord, perfect for us our light.",
        "Ô notre Seigneur, parachève notre lumière.",
        "تمام النور يوم القيامة.",
        ["guidance", "success"],
        ["light", "نور"],
    ),
    dua(
        "q_4_147",
        "مَّا يَفْعَلُ اللَّهُ بِعَذَابِكُمْ إِن شَكَرْتُمْ وَآمَنتُمْ ۚ وَكَانَ اللَّهُ شَاكِرًا عَلِيمًا",
        4,
        147,
        "What would Allah do with punishing you if you are grateful and believe? And Allah is Appreciative and Knowing.",
        "Que ferait Allah à vous punir si vous êtes reconnaissants et croyants ? Allah est Reconnaissant et Omniscient.",
        "شكر الإيمان وطلب العفو من العذاب.",
        ["gratitude", "forgiveness", "guidance"],
        ["shukr", "grateful", "شكر"],
    ),
    dua(
        "q_6_162",
        "قُلْ إِنَّ صَلَاتِي وَنُسُكِي وَمَحْيَايَ وَمَمَاتِي لِلَّهِ رَبِّ الْعَالَمِينَ",
        6,
        162,
        "Say, indeed, my prayer, my rites, my living and my dying are for Allah, Lord of the worlds.",
        "Dis : ma prière, mes rites, ma vie et ma mort appartiennent à Allah, Seigneur des mondes.",
        "إخلاص العبادة لله.",
        ["guidance", "gratitude", "taqwa"],
        ["worship", "dedication", "إخلاص"],
    ),
    dua(
        "q_7_89",
        "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
        7,
        89,
        "Sufficient for us is Allah, and He is the best Disposer of affairs.",
        "Allah nous suffit : quel excellent garant !",
        "توكل شعيب وقومه على الله.",
        ["refuge", "protection", "patience"],
        ["Shuayb", "hasbunallah"],
    ),
    dua(
        "q_10_85",
        "رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَتَوَفَّنَا مُسْلِمِينَ",
        10,
        85,
        "Our Lord, pour upon us patience and cause us to die as Muslims.",
        "Ô notre Seigneur, déverse sur nous la patience et fais-nous mourir en musulmans.",
        "صبر وحسن الخاتمة.",
        ["patience", "guidance", "success"],
        ["Muslim", "death", "صبر"],
    ),
    dua(
        "q_11_45",
        "رَبِّ اغْفِرْ لِي وَلِوَالِدَيَّ وَلِمَن دَخَلَ بَيْتِيَ مُؤْمِنًا",
        11,
        45,
        "My Lord, forgive me and my parents and whoever enters my house believing.",
        "Ô mon Seigneur, pardonne-moi, à mes parents et à quiconque entre ma demeure croyant.",
        "استغفار نوح لمن آمن.",
        ["forgiveness", "parents", "mercy"],
        ["Nuh", "house", "believer"],
    ),
    dua(
        "q_12_33",
        "رَبِّ السِّجْنُ أَحَبُّ إِلَيَّ مِمَّا يَدْعُونَنِي إِلَيْهِ",
        12,
        33,
        "My Lord, prison is more to my liking than that to which they invite me.",
        "Ô mon Seigneur, la prison m’est plus chère que ce à quoi ils m’appellent.",
        "دعاء يوسف: العصمة من الفتنة.",
        ["protection", "guidance", "patience"],
        ["Yusuf", "trial", "prison"],
    ),
    dua(
        "q_14_35b",
        "رَبَّنَا إِنِّي أَسْكَنتُ مِن ذُرِّيَّتِي بِوَادٍ غَيْرِ ذِي زَرْعٍ عِندَ بَيْتِكَ الْمُحَرَّمِ",
        14,
        37,
        "Our Lord, I have settled some of my descendants in an uncultivated valley near Your sacred House.",
        "Ô notre Seigneur, j’ai établi une partie de ma descendance dans une vallée stérile près de Ta Maison sacrée.",
        "دعاء إبراهيم لمن سكن مكة.",
        ["parents", "rizq", "guidance"],
        ["Makkah", "Hajar", "Ismail"],
    ),
    dua(
        "q_16_30b",
        "رَبَّنَا وَآتِنَا مَا وَعَدتَّنَا عَلَىٰ رُسُلِكَ",
        3,
        194,
        "Our Lord, grant us what You promised us through Your messengers.",
        "Ô notre Seigneur, accorde-nous ce que Tu as promis par Tes messagers.",
        "طلب تحقيق وعد الله.",
        ["success", "guidance", "mercy"],
        ["promise", "messengers"],
    ),
    dua(
        "q_24_35",
        "اللَّهُ نُورُ السَّمَاوَاتِ وَالْأَرْضِ",
        24,
        35,
        "Allah is the Light of the heavens and the earth.",
        "Allah est la Lumière des cieux et de la terre.",
        "التأمل في نور الله (آية النور).",
        ["guidance", "knowledge"],
        ["light", "nur", "نور"],
    ),
    dua(
        "q_35_15",
        "يَا أَيُّهَا النَّاسُ أَنتُمُ الْفُقَرَاءُ إِلَى اللَّهِ ۖ وَاللَّهُ هُوَ الْغَنِيُّ الْحَمِيدُ",
        35,
        15,
        "O mankind, you are those in need of Allah, while Allah is the Free of need, the Praiseworthy.",
        "Ô hommes, vous êtes les indigents vis-à-vis d’Allah ; Lui est le Riche, le Digne de louange.",
        "الافتقار إلى الله والرجاء في رزقه.",
        ["rizq", "gratitude", "guidance"],
        ["need", "poor", "فقر", "provision"],
    ),
    dua(
        "q_39_46",
        "اللَّهُمَّ فَاطِرَ السَّمَاوَاتِ وَالْأَرْضِ أَنتَ وَلِيِّي فِي الدُّنْيَا وَالْآخِرَةِ",
        39,
        46,
        "O Allah, Creator of the heavens and earth, You are my protector in this world and the Hereafter.",
        "Ô Allah, Créateur des cieux et de la terre, Tu es mon protecteur ici-bas et dans l’au-delà.",
        "التوكل والولاية لله.",
        ["protection", "guidance", "refuge"],
        ["wali", "creator", "ولي"],
    ),
    dua(
        "q_65_2_3",
        "وَمَن يَتَّقِ اللَّهَ يَجْعَل لَّهُ مَخْرَجًا * وَيَرْزُقْهُ مِنْ حَيْثُ لَا يَحْتَسِبُ",
        65,
        2,
        "Whoever fears Allah — He will make for him a way out and provide for him from where he does not expect.",
        "Quiconque craint Allah, Il lui donnera une issue et le pourvoira d’où il n’attend pas.",
        "تقوى الله تفتح الرزق والفرج.",
        ["rizq", "success", "taqwa"],
        ["tawqa", "makhraj", "provision", "رزق"],
        ayah_end=3,
    ),
]


def main():
    with OUT.open(encoding="utf-8") as f:
        data = json.load(f)
    existing = {x["id"] for x in data["items"]}
    merged = list(data["items"])
    for d in EXTRA:
        if d["id"] in existing:
            continue
        merged.append(d)
        existing.add(d["id"])
    data["items"] = merged
    data["version"] = 2
    with OUT.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"Total duas: {len(merged)}")


if __name__ == "__main__":
    main()
